/*:

Public Extension Table of Contents

- [AbsoluteValuable](AbsoluteValuable)
- [Array](Array)
- [BidirectionalCollection](BidirectionalCollection)
- [Bool](Bool)
- [Cache](Cache)
- [CGSize](CGSize)
- [CGRect](CGRect)
- [CharacterSet](CharacterSet)
- [Collection](Collection)
- [Comparable](Comparable)
- [CountableRange](Range)
- [Date](Date)
- [DateFormatter](DateFormatter)
- [Dictionary](Dictionary)
- [ErrorType](ErrorType)
- [FloatingPoint](FloatingPoint)
- [Int](Int)
- [OperationQueue](OperationQueue)
- [Optional](Optional)
- [Playground%20Related](Playground%20Related)
- [Miscellaneous](Miscellaneous)
- [NSObject](NSObject)
- [RandomAccessCollection](RandomAccessCollection)
- [Result](Result)
- [String](String)
- [Sequence](Sequence)
- [StringLiteralConvertible](StringLiteralConvertible)
- [Timer](Timer)
- [UIAlertController](UIAlertController)
- [UICollectionView](UICollectionView)
- [UIColor](UIColor)
- [UIDynamicAnimator](UIDynamicAnimator)
- [UIEdgeInsets](UIEdgeInsets)
- [UIGestureRecognizer](UIGestureRecognizer)
- [UIImage](UIImage)
- [UInt](UInt)
- [UIOffset](UIOffset)
- [UIFont](UIFont)
- [UIScrollView](UIScrollView)
- [UISplitViewController](UISplitViewController)
- [UITableView](UITableView)
- [UIView](UIView)
- [UIWindow](UIWindow
- [UnicodeScalar](UnicodeScalar)
- [UserDefaults](UserDefaults)

*/
