/*:

Public Extension (iOS) Table of Contents

- [AbsoluteValuable](AbsoluteValuable)
- [Array](Array)
- [Bool](Bool)
- [CGSize](CGSize)
- [CGRect](CGRect)
- [CollectionType](CollectionType)
- [Comparable](Comparable)
- [Dictionary](Dictionary)
- [ErrorType](ErrorType)
- [Int](Int)
- [Optional](Optional)
- [Playground%20Related](Playground%20Related)
- [Miscellaneous](Miscellaneous)
- [NSCache](NSCache)
- [NSCharacterSet](NSCharacterSet)
- [NSDate](NSDate)
- [NSDateFormatter](NSDateFormatter)
- [NSObject](NSObject)
- [NSOperationQueue](NSOperationQueue)
- [NSRange](NSRange)
- [NSTimer](NSTimer)
- [NSUserDefaults](NSUserDefaults)
- [Range](Range)
- [Result](Result)
- [String](String)
- [SequenceType](SequenceType)
- [UICollectionView](UICollectionView)
- [UIColor](UIColor)
- [UIDynamicAnimator](UIDynamicAnimator)
- [UIEdgeInsets](UIEdgeInsets)
- [UIGestureRecognizer](UIGestureRecognizer)
- [UIImage](UIImage)
- [UInt](UInt)
- [UIOffset](UIOffset)
- [UIFont](UIFont)
- [UIScrollView](UIScrollView)
- [UISplitViewController](UISplitViewController)
- [UITableView](UITableView)
- [UIView](UIView)
- [UIWindow](UIWindow)

*/
